### PR TITLE
Make ApiRespose static

### PR DESCRIPTION
**Pull request by aaronjameslang**
I took some liberties with this, but it's easier to show you than try to explain it

Let me know what you think

### CODE REVIEW

**Comment by gojko** [comment]
this looks pretty good to me. I'm a bit distracted this week due to a lot of travel, but I'll merge it once things quiet down, I just want to run a few more tests.

**Comment by aaronjameslang** [comment]
Great, thanks for the feedback

**Comment by robertkeizer** [comment]
This PR should also clear up an issue I had to hack around. The following line forced a single instance of ApiBuilder to be used wherever an ApiResponse is required. I ended up global'ing an instance of ApiBuilder so that the prototype would match.


 * https://github.com/claudiajs/claudia-api-builder/pull/49/files#diff-1cf617c7320e41a12e5604cac8016c60R54 


The line above could be changed to use `instanceof` which might be a bit more intuitive, although the PR should take care of it as well.

**Comment by gojko** [comment]
thanks, this is now on NPM as 4.1.0

**Pull request merged**
