### PR TITLE
implements route params for proxyRouter

### PR DESCRIPTION
**Pull request by khalidhoffman**
Should make it easier for use of route params with the proxy router

### CODE REVIEW

**Comment by gojko** [comment]
Hi,

before merging this, can you please add tests for your changes as well. 

What are you trying to achieve with this? eg can you add an example of how this will be used? dynamic path parameters are already supported, so if you did this just to implement that, the change isn't necessary.

**Comment by khalidhoffman** [comment]
Sorry for the lack of info. I've been meaning to share this awhile ago. I had done some work similar to my pull request but lost all of it, so I had to start anew (I forgot to add the auto population of path params values in the first commit). My personal use case came from running a local server than uses the `proxyRouter` method.

Something like:
```
app.get(/.*/, (req, res) => {
	var requestData = getAdwordsReport = {
		requestContext: {
			httpMethod: req.method,
			resourcePath: req.url
		}
	};

	api.proxyRouter(requestData, {
		done: function (err, resp) {
			res.send(resp.body);
		}
	});
});
```
which would fail if path parameters are used. One would have to parse the url themselves and assign it to `pathParameters` according to the predefined route.

**Comment by gojko** [comment]
I'm not entirely sure this is particularly useful in a generic case to include into claudia. I'd like to hear what other people think before merging.

btw, you can create an interceptor in your API and translate whatever is coming in to a valid API gateway request, and it will be routed after the intercept transformation. For cases like the one you describe, where I assume you want to run claudia outside Lambda, that would be the best way to do it without having to patch the api builder code.

**Comment by khalidhoffman** [comment]
Right, and I've done something similar on multiple occasions. It seemed like a feature that should be included with the proxyRouter out of the box. Pretty much all nodejs server packages include this with their routers. That said, I acknowledge the proxyRouter was not intended to serve as standalone server. I just thought it would be helpful for others.

**Comment by gojko** [comment]
Hi,

I had a chat with the other core devs on this, and we decided that it's best not to merge it. Making it work fully inside Lambda would require changes to the claudiajs deployment utility as well (as nothing would create regex routes now, or even worse would try to create those routes literally, not as a regex). There are too many edge cases that could come up as a result of regular, proxy and regex routes clashing that we'd have to somehow handle, and would potentially be incompatible with how API GW handles route conflicts, so this definitely goes beyond the 'no magic' design guideline. 

While this is a good feature for a generic HTTP router, and would likely help with testing APIs locally, Claudia API builder is first and foremost a deployment utility for AWS Lambda, so things like this are best kept outside the core.

**Pull request closed without merging**
