### PR TITLE
fix: correctly route paths with parameters

### PR DESCRIPTION
**Pull request by aaronjameslang**

### CODE REVIEW

**Comment by aaronjameslang** [comment]
Added `.nvmrc` as well to make it easier to test locally using correct version

**Comment by gojko** [comment]
hi, we test using several vms, so committing .nvmrc isn't a good idea for the main repo. feel free to keep it in your local repo, though.

**Comment by aaronjameslang** [comment]
OK will update

What do you think of the rest of it?

**Comment by gojko** [comment]
i'm a bit confused by all the routing changes as I was convinced that worked OK. I don't really like using `path || resource`, so we'll do it if we really need to, but it should be possible to route just based on a single field. I want to do a small test first before merging and try all these combinations on actual lambda+api gw with both claudia and API_GW request types and see if we can use a single field for routing.

**Comment by aaronjameslang** [comment]
It would be great if we could rely on one field but I'm not sure we can

We need `path` to map `/pets/cats` -> `/pets/{type}` -> `/pets/cats` and `users/likes` -> `/users/{+all}` -> `users/likes`

But we also need `resource` to map `/users/23` -> `/users/{userId}` -> `/users/{userId}`

The only limitation after this is that we can't do `/users/23/stars` -> `/users/{+extras}` -> `/users/{userId}/stars`, I don't know if this last case would be worth the complexity

Thanks for taking the time to look at these changes 😄

**Comment by gojko** [comment]
last time I looked at this (and it was a while ago), api gateway would not let you set up ambiguous routes, so you could not do `/users/{+all}` and `/users/{userId}` at the same time. I'll set up a test project soon and run it on api g to see if things changed

**Comment by gojko** [comment]
I still get this error when trying to create ambiguous resources in us-east-1:

```
creating REST API	apigateway.setAcceptHeader
{ BadRequestException: A sibling ({all+}) of this resource already has a variable path part -- only one is allowed
```
 
How are you able to create ambiguous path resources (`/users/{all+}` and `/users/{userId}`) ?

**Comment by gojko** [comment]
Hi,

I've set up a demo project with the routes (apart from the ambiguous one that API Gateway rejects): https://github.com/gojko/claudia-web-routing -- using this, I could see routes correctly working for both AWS_PROXY and CLAUDIA_API_BUILDER request types for all mentioned paths. Can you please add an example that breaks it so I know what we're actually fixing here?

the patch you submitted previously in https://github.com/claudiajs/claudia-api-builder/pull/51 actually breaks routing for AWS_PROXY, so I reverted it back. You can see this easily by changing the version of api builder in package.json to 4.1.0 and redeploying with `npm run update`

**Comment by aaronjameslang** [comment]
You're right that you can't define all those ambiguous paths in the same api, but you can define any of them.

Reworded for clarity:
> We need path to map `/pets/cats` -> `/pets/{type}` -> `/pets/cats` and `photos/likes` -> `/photos/{+all}` -> `photos/likes`
>
> But we also need resource to map `/customers/23` -> `/customers/{customerId}` -> `/customers/{customersId}`
>
> The only limitation after this is that we can't do `/articles/23/stars` -> `/articles/{+extras}` -> `/articles/{articleId}/stars`, I don't know if this last case would be worth the complexity

I'll add an example to https://github.com/gojko/claudia-web-routing, and add the appropriate parts of #51 to this so we can consider them all together

**Comment by aaronjameslang** [comment]
I haven't added an example to https://github.com/gojko/claudia-web-routing as I'm not sure it can be reproduced like that. It would require an entry in the api gateway like `/pets/{type}` but a route in claudia like `api.get('/pets/cats', ...)`. I've added tests to this PR that do reproduce the issue.

**Comment by gojko** [comment]
so are you managing api gateway outside of claudia? How do you create a route in api gw like /pets/{type} with a route in claudia as '/pets/cats'?

**Comment by aaronjameslang** [comment]
Yeh, several of the projects I work with/on don't use claudia but find claudia-api-builder perfect for routing. Hopefully that answers both questions, let me know if not.

**Comment by gojko** [comment]
ok, that makes it clear why we're having these problems :) 

claudia api builder is designed to have a 1:1 mapping between the api gateway and it's own routes. Anything else really opens a can of worms so it may work for a subset of what you need, but many of the features such as content conversion, authorisers, CORS shortcuts and  optimisations won't work unless claudia sets it up. so this is out of scope of what we intended with api builder.

I think this is an interesting use case but I don't have the capacity to test and support it properly. doing it so all api builder features work requires moving too much responsibility into api builder, and that defeats the point of it being a minimalist runtime dependency for claudia. 

I think the best course of action would be for you to fork the api builder and just keep the routing part, delete everything else, and maintain your own minimalist router based on it. if other people have the same need.

**Pull request closed without merging**
