### PR TITLE
Add API GW requestId to requestContext

### PR DESCRIPTION
**Pull request by agon21**
I have the need of  matching Lambda and API GW requestID in the logs. So I would like to pass my Lambda the API GW requestId through request.context.requestId.

I actually wonder why the whole requestContext is not exposed, and `convertContext ` is called to only show desired files. Could you please answer me that question? I think in some use cases, there are more API GW fields that can be helpful to be accessible in Lambda
Thank you

### CODE REVIEW

**Comment by gojko** [comment]
for historical reasons - claudia api builder was built before api gw had a proxy integration, and the field names/object structure does not match 100%. 

we did not want to break backwards compatibility after the proxy integration was implemented, so by default things work as they did. 

You can get a straight pass-through by setting the request type when you initialise the API builder

```
var ApiBuilder = require('claudia-api-builder'),
	api = new ApiBuilder('AWS_PROXY');
```
It seems that will be a much better way of solving your problem, as then you get all the fields from the API GW request, without any conversion. let me know if that's enough, in which case I'll close this pull request without merging

**Comment by agon21** [comment]
Tank you for your answer @gojko 
By implementing what you say, it seems I can get over my problem. But the way to access API GW requestId in my Lambda will then be the following?:

`request.requestId`

Or will it be nested under any other field?
thanks

**Comment by gojko** [comment]
the request is the whole AWS request, so the ID would most likely be request.requestContext.requestId. you'll need to check the AWS proxy request object docs for the details.

**Comment by agon21** [comment]
Just to note, by using 
`var ApiBuilder = require('claudia-api-builder'),
	api = new ApiBuilder('AWS_PROXY');`

the API GW requestId is accessible in the Lambda within the following object:

`request.proxyRequest.requestContext.requestId`

Thanks for your help on this :grinning:

**Pull request closed without merging**
