### PR TITLE
Adds all API Gateway supported http methods

### PR DESCRIPTION
**Pull request by mikefrey**
Adds support for the following HTTP methods:

DELETE
HEAD
OPTIONS
PATCH

### CODE REVIEW

**Comment by gojko** [comment]
Thanks for this. At the moment, we're handling OPTIONS in a generic way (CORS is automatically set to '*'). Is there a reason you need to specify it separately? That might create a conflict with `rebuildWebApi` (https://github.com/claudiajs/claudia/blob/master/src/tasks/rebuild-web-api.js#L158). If not, it's probably safest if we leave that one out for the moment.

**Comment by mikefrey** [comment]
I was really just looking for DELETE and PATCH support, I thought I'd add the other two just to cover everything. I'll remove OPTIONS if you feels it's best.

**Comment by gojko** [comment]
that would make it possible for me to publish the new api builder version tonight. otherwise, i'll have to figure out how to avoid conflicts with the generic options handler tomorrow or on monday. I guess let's leave that out and when someone needs the options handler, we'll deal with that then

**Comment by mikefrey** [comment]
@gojko OPTIONS has been removed.

**Comment by gojko** [comment]
ok, pushed to NPM as 1.0.2!

**Comment by mikefrey** [comment]
Thanks! And thank you for the great library!

**Comment by gojko** [comment]
Thanks for contributing!

**Pull request merged**
