### PR TITLE
fix: correctly route greedy proxy paths

### PR DESCRIPTION
**Pull request by aaronjameslang**
example of error:
  https://github.com/aaronjameslang/sscce-claudia-sam-greedy-proxy

### CODE REVIEW

**Comment by gojko** [comment]
hi - this looks good, but can I just check something before merging -- if I understand the pull req correctly, this fixes an issue when using the API_GW request type with Sam Local? Or is this a wider problem you caught when running actually in Lambda?

**Comment by aaronjameslang** [comment]
I noticed this bug after upgrading from sam 0.2.11 to 0.3.0, and assumed it was sam. After investigating, sam's changes bring it in line with how lambda actually works. This error is reproducible on real lamdas.

:)

**Comment by gojko** [comment]
thanks, this is now on NPM as 4.1.0

**Comment by gojko** [comment]
i've reverted this back, as it breaks AWS_PROXY routing in us-east-1. this is removed from 4.1.1 on npm, i'll test it properly over the next few days and see if it needs to be changed for merging

**Comment by aaronjameslang** [comment]
OK, anything we decide to keep I'll include in #53, so we can consider them together and keep discussion in one place

**Pull request merged**
